package com.healthcare.vitalsync.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "health_reports")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class HealthReport {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Supabase Storage URL for the uploaded image */
    @Column(nullable = false)
    private String fileUrl;

    private String fileType;   // e.g. "image/jpeg", "application/pdf"

    /** Raw text extracted by Gemini Vision */
    @Column(columnDefinition = "TEXT")
    private String rawExtractedText;

    /** HuggingFace Model Analysis */
    @Column(columnDefinition = "TEXT")
    private String hfAnalysis;

    /** "Friendly Coach" summary generated by Gemini */
    @Column(columnDefinition = "TEXT")
    private String geminiSummary;

    /** Structured JSON of key-value vitals extracted (e.g. {"hemoglobin":"12.5"}) */
    @Column(columnDefinition = "TEXT")
    private String extractedMetrics;

    /** Set to true if any value exceeded SOS thresholds */
    @Builder.Default
    private boolean criticalFlagged = false;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime uploadedAt;
}
